version: '3.9'

services:

  drupal:
    build: .
    ports:
      - 8080:80
    restart: always
    environment: 
      DRUPAL_DATABASE_HOST: myql
      DRUPAL_DATABASE_NAME: drupal8
      DRUPAL_DATABASE_PASSWORD: root
      DRUPAL_DATABASE_PORT: "3306"
      DRUPAL_DATABASE_USERNAME: root
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      FACEBOOK_CLIENT_ID: 
      FACEBOOK_CLIENT_SECRET: 

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal